<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>vn.edu.nhom7</groupId><artifactId>quiz-arena</artifactId><version>1.0.0-SNAPSHOT</version></parent><artifactId>quiz-arena-client</artifactId><dependencies><dependency><groupId>vn.edu.nhom7</groupId><artifactId>quiz-arena-common</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.openjfx</groupId><artifactId>javafx-controls</artifactId></dependency></dependencies><build><plugins><plugin><groupId>org.openjfx</groupId><artifactId>javafx-maven-plugin</artifactId><configuration><mainClass>vn.edu.nhom7.quiz.client.ClientMain</mainClass></configuration></plugin></plugins></build></project>
