-- MySQL 8.4; apply in the selected empty schema. All application timestamps UTC.
CREATE TABLE IF NOT EXISTS SCHEMA_METADATA (version INT PRIMARY KEY, asset_pack_version VARCHAR(32) NOT NULL);
INSERT IGNORE INTO SCHEMA_METADATA VALUES (1,'1');
CREATE TABLE IF NOT EXISTS USERS (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 display_name VARCHAR(128) NOT NULL, avatar_id VARCHAR(64) NOT NULL, password_hash VARCHAR(255) NOT NULL,
 total_score BIGINT NOT NULL DEFAULT 0,total_matches INT NOT NULL DEFAULT 0,wins INT NOT NULL DEFAULT 0,losses INT NOT NULL DEFAULT 0,draws INT NOT NULL DEFAULT 0,created_at DATETIME(3) NOT NULL,
 CHECK(total_score>=0 AND total_matches>=0 AND wins>=0 AND losses>=0 AND draws>=0), CHECK(total_matches=wins+losses+draws), INDEX idx_users_ranking(total_score DESC,wins DESC,id ASC)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS CATEGORIES(id BIGINT PRIMARY KEY,name VARCHAR(128) NOT NULL UNIQUE,display_order INT NOT NULL,is_active BOOLEAN NOT NULL) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS QUIZZES(id BIGINT PRIMARY KEY,category_id BIGINT NOT NULL,title VARCHAR(128) NOT NULL,description VARCHAR(1000) NOT NULL,cover_asset_id VARCHAR(64),is_active BOOLEAN NOT NULL,created_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL,FOREIGN KEY(category_id) REFERENCES CATEGORIES(id)) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS QUESTIONS(id BIGINT PRIMARY KEY,quiz_id BIGINT NOT NULL,question_type VARCHAR(32) NOT NULL,content TEXT NOT NULL,options_json JSON NOT NULL,answer_key_json JSON NOT NULL,explanation TEXT,question_asset_id VARCHAR(64),explanation_asset_id VARCHAR(64),is_active BOOLEAN NOT NULL,created_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL,FOREIGN KEY(quiz_id) REFERENCES QUIZZES(id),CHECK(question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER')),INDEX idx_questions_available(quiz_id,is_active,question_type)) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS MATCHES(id CHAR(36) CHARACTER SET ascii PRIMARY KEY,quiz_id BIGINT NOT NULL,quiz_title_snapshot VARCHAR(128) NOT NULL,player1_id BIGINT NOT NULL,player2_id BIGINT NOT NULL,player1_name_snapshot VARCHAR(128) NOT NULL,player2_name_snapshot VARCHAR(128) NOT NULL,score1 INT NOT NULL,score2 INT NOT NULL,correct_count1 INT NOT NULL,correct_count2 INT NOT NULL,outcome VARCHAR(32) NOT NULL,finish_reason VARCHAR(32) NOT NULL,reason_code VARCHAR(64),started_at DATETIME(3) NOT NULL,ended_at DATETIME(3) NOT NULL,completed_rounds INT NOT NULL,opened_rounds INT NOT NULL,FOREIGN KEY(quiz_id) REFERENCES QUIZZES(id),FOREIGN KEY(player1_id) REFERENCES USERS(id),FOREIGN KEY(player2_id) REFERENCES USERS(id),CHECK(player1_id<>player2_id),CHECK(score1 BETWEEN 0 AND 30 AND score2 BETWEEN 0 AND 30),CHECK(correct_count1 BETWEEN 0 AND 10 AND correct_count2 BETWEEN 0 AND 10),CHECK(completed_rounds BETWEEN 0 AND 10 AND opened_rounds BETWEEN completed_rounds AND 10),CHECK(outcome IN ('PLAYER1_WIN','PLAYER2_WIN','DRAW','NONE')),CHECK(finish_reason IN ('COMPLETED','FORFEIT','ABORTED')),INDEX idx_matches_p1(player1_id,ended_at DESC,id),INDEX idx_matches_p2(player2_id,ended_at DESC,id)) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS MATCH_QUESTIONS(round_id CHAR(36) CHARACTER SET ascii PRIMARY KEY,match_id CHAR(36) CHARACTER SET ascii NOT NULL,round_index INT NOT NULL,question_id BIGINT NOT NULL,question_snapshot_json JSON NOT NULL,revealed BOOLEAN NOT NULL,FOREIGN KEY(match_id) REFERENCES MATCHES(id),FOREIGN KEY(question_id) REFERENCES QUESTIONS(id),UNIQUE KEY uq_match_round(match_id,round_index),CHECK(round_index BETWEEN 1 AND 10),INDEX idx_mq_question(question_id)) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS MATCH_ANSWERS(id BIGINT PRIMARY KEY AUTO_INCREMENT,round_id CHAR(36) CHARACTER SET ascii NOT NULL,user_id BIGINT NOT NULL,answer_json JSON,answer_time_ms BIGINT,received_at DATETIME(3),outcome VARCHAR(32) NOT NULL,is_correct BOOLEAN,earned_points INT NOT NULL,request_id CHAR(36) CHARACTER SET ascii,FOREIGN KEY(round_id) REFERENCES MATCH_QUESTIONS(round_id),FOREIGN KEY(user_id) REFERENCES USERS(id),UNIQUE KEY uq_round_user(round_id,user_id),INDEX idx_ma_user(user_id),CHECK(earned_points BETWEEN 0 AND 3),CHECK(answer_time_ms IS NULL OR answer_time_ms>=0),CHECK((outcome='ANSWERED' AND is_correct IS NOT NULL AND answer_json IS NOT NULL AND answer_time_ms IS NOT NULL) OR (outcome='TIMEOUT' AND is_correct IS NOT NULL AND is_correct=FALSE AND answer_json IS NULL AND answer_time_ms IS NULL AND earned_points=0) OR (outcome='ABANDONED' AND is_correct IS NULL AND earned_points=0))) CHARACTER SET utf8mb4;
