-- Upgrade existing MySQL 8.4 schema once, after 001 and 002; preserves all fixed IDs.
-- Only auto-increment metadata changes; retain all existing foreign key definitions.
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE QUIZZES MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
 ADD quiz_source VARCHAR(16) NOT NULL DEFAULT 'SYSTEM', ADD owner_id BIGINT NULL,
 ADD public_version_id BIGINT NULL, ADD FOREIGN KEY(owner_id) REFERENCES USERS(id),
 ADD CHECK(quiz_source IN ('SYSTEM','COMMUNITY'));
ALTER TABLE QUESTIONS MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE MEDIA_ASSETS(id VARCHAR(64) PRIMARY KEY,owner_id BIGINT NOT NULL,mime_type VARCHAR(32) NOT NULL,byte_size INT NOT NULL,sha256 CHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL,FOREIGN KEY(owner_id) REFERENCES USERS(id)) CHARACTER SET utf8mb4;
CREATE TABLE QUIZ_DRAFTS(quiz_id BIGINT PRIMARY KEY,title VARCHAR(128) NOT NULL,description VARCHAR(1000) NOT NULL,category_id BIGINT NOT NULL,shuffle_questions BOOLEAN NOT NULL DEFAULT FALSE,FOREIGN KEY(quiz_id) REFERENCES QUIZZES(id),FOREIGN KEY(category_id) REFERENCES CATEGORIES(id)) CHARACTER SET utf8mb4;
CREATE TABLE QUIZ_DRAFT_QUESTIONS(quiz_id BIGINT NOT NULL,position INT NOT NULL,question_json JSON NOT NULL,PRIMARY KEY(quiz_id,position),FOREIGN KEY(quiz_id) REFERENCES QUIZ_DRAFTS(quiz_id),CHECK(position BETWEEN 0 AND 49)) CHARACTER SET utf8mb4;
CREATE TABLE QUIZ_VERSIONS(id BIGINT PRIMARY KEY AUTO_INCREMENT,quiz_id BIGINT NOT NULL,title VARCHAR(128) NOT NULL,description VARCHAR(1000) NOT NULL,category_id BIGINT NOT NULL,shuffle_questions BOOLEAN NOT NULL,created_at DATETIME(3) NOT NULL,FOREIGN KEY(quiz_id) REFERENCES QUIZZES(id),FOREIGN KEY(category_id) REFERENCES CATEGORIES(id)) CHARACTER SET utf8mb4;
CREATE TABLE QUIZ_VERSION_QUESTIONS(version_id BIGINT NOT NULL,position INT NOT NULL,question_id BIGINT NOT NULL,PRIMARY KEY(version_id,position),FOREIGN KEY(version_id) REFERENCES QUIZ_VERSIONS(id),FOREIGN KEY(question_id) REFERENCES QUESTIONS(id),CHECK(position BETWEEN 0 AND 49)) CHARACTER SET utf8mb4;
ALTER TABLE QUIZZES ADD FOREIGN KEY(public_version_id) REFERENCES QUIZ_VERSIONS(id);
ALTER TABLE MATCHES ADD ranked BOOLEAN NOT NULL DEFAULT TRUE,ADD quiz_version_id BIGINT NULL,ADD total_rounds INT NOT NULL DEFAULT 10,ADD FOREIGN KEY(quiz_version_id) REFERENCES QUIZ_VERSIONS(id);
-- Discover legacy generated CHECK names rather than depending on name allocation.
SET @drop_match_checks=(SELECT CONCAT('ALTER TABLE MATCHES ',GROUP_CONCAT(CONCAT('DROP CHECK `',tc.CONSTRAINT_NAME,'`') SEPARATOR ',')) FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME='MATCHES' AND tc.CONSTRAINT_TYPE='CHECK' AND (cc.CHECK_CLAUSE LIKE '%score1%' OR cc.CHECK_CLAUSE LIKE '%correct_count1%' OR cc.CHECK_CLAUSE LIKE '%completed_rounds%'));
PREPARE community_migration FROM @drop_match_checks;
EXECUTE community_migration;
DEALLOCATE PREPARE community_migration;
ALTER TABLE MATCHES
 ADD CONSTRAINT chk_matches_scores CHECK(score1 BETWEEN 0 AND 150 AND score2 BETWEEN 0 AND 150),
 ADD CONSTRAINT chk_matches_correct CHECK(correct_count1 BETWEEN 0 AND 50 AND correct_count2 BETWEEN 0 AND 50),
 ADD CONSTRAINT chk_matches_rounds CHECK(total_rounds BETWEEN 1 AND 50 AND completed_rounds BETWEEN 0 AND total_rounds AND opened_rounds BETWEEN completed_rounds AND total_rounds);
SET @drop_round_checks=(SELECT CONCAT('ALTER TABLE MATCH_QUESTIONS ',GROUP_CONCAT(CONCAT('DROP CHECK `',tc.CONSTRAINT_NAME,'`') SEPARATOR ',')) FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME='MATCH_QUESTIONS' AND tc.CONSTRAINT_TYPE='CHECK' AND cc.CHECK_CLAUSE LIKE '%round_index%');
PREPARE community_migration FROM @drop_round_checks;
EXECUTE community_migration;
DEALLOCATE PREPARE community_migration;
ALTER TABLE MATCH_QUESTIONS ADD CONSTRAINT chk_mq_round CHECK(round_index BETWEEN 1 AND 50);
UPDATE SCHEMA_METADATA SET version=3;
